# Generated by Django 5.1.6 on 2025-02-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='audio_bitrate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hdmi_audio_output',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hdmi_video_output',
        ),
        migrations.RemoveField(
            model_name='product',
            name='incoming_bandwidth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outgoing_bandwidth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rca_audio_output',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vga_audio_output',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vga_video_output',
        ),
    ]
