# Generated by Django 5.1.6 on 2025-02-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_audio_bitrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='decoding_format',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ip_video_input',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lens_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='poe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recording_resolution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sata',
        ),
    ]
