# Generated by Django 5.1.6 on 2025-02-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_decoding_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='network_interface',
        ),
    ]
